# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/node:10.6

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mongo:3.4.4

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "frontend/package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "backend/package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: npm install --ignore-scripts
            - run:
                  command: npm install
                  working_directory: frontend
            - run:
                  command: npm install
                  working_directory: backend

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - save_cache:
                  paths:
                      - frontend/node_modules
                  key: v1-dependencies-{{ checksum "frontend/package.json" }}
            - save_cache:
                  paths:
                      - backend/node_modules
                  key: v1-dependencies-{{ checksum "backend/package.json" }}

            # run tests!
            - store_artifacts:
                  path: frontend/src/__tests__/constants.test.js
                  destination: constants.test.js
             - store_artifacts:
                  path: frontend/src/__tests__/frontend.test.js
                  destination: frontend.test.js
            - store_artifacts:
                  path: backend/src/__tests__/backend.test.js
                  destination: backend.test.js
            - run:
                  command: npm test
                  working_directory: backend
            - run:
                  command: npm test -- --watchAll=false
                  working_directory: frontend
